# Generated by Django 3.1.7 on 2021-02-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname_student',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname_student',
            field=models.CharField(max_length=20),
        ),
    ]
