# Generated by Django 3.1.7 on 2021-02-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210227_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='purchases',
        ),
        migrations.AddField(
            model_name='basket',
            name='purchases',
            field=models.ManyToManyField(to='blog.Product'),
        ),
    ]
