# Generated by Django 3.1.7 on 2021-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210224_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='Book', to='blog.Book'),
        ),
    ]
