# Generated by Django 3.1.7 on 2021-02-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210227_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=0, max_length=15, null=None),
            preserve_default=False,
        ),
    ]
