# Generated by Django 3.1.7 on 2021-02-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210224_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='book',
            field=models.ManyToManyField(related_name='Book', to='blog.Book'),
        ),
    ]
