# Generated by Django 3.1.7 on 2021-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prise',
            field=models.FloatField(),
        ),
    ]
